version: "3.9"
services:
    postgres:
        image: postgres:11
        container_name: postgres
        ports:
            - 5432:5432
        env_file:
            - ./postgres/postgres.env
        volumes:
            - pgdata:/var/lib/postgresql/data
            - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
volumes:
  pgdata:
